kind: pipeline
type: docker
name: flake8

steps:
- name: flake8
  image: python:3.7-buster
  commands:
  - apt-get update
  - apt-get install -y python3-flake8 flake8
  - flake8 src test setup.py

---

kind: pipeline
type: docker
name: tests

steps:
- name: tests
  image: python:3.7-buster
  commands:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install -y xvfb libgles2-mesa ghostscript gmt gmt-gshhg poppler-utils
  - apt-get install -y python3-pyqt5
  - pip install -r requirements-all.txt
  - pip install PyQt5
  - python3 setup.py install -f
  - pip install utm
  - pip install git+https://github.com/pyrocko/kite
  - pip install obspy
  - xvfb-run -s '-screen 0 640x480x24' python3 -m nose test
